export const UsersActionTypes ={
    FETCH_USERS_START:"FETCH_USERS_START",
    FETCH_USERS_SUCCESS:"FETCH_USERS_SUCCESS",
    FETCH_USERS_FAILURE:"FETCH_USERS_FAILURE",
    CREATE_USER_FAILURE:"CREATE_USER_FAILURE"

}